import { NgModule } from '@angular/core';

import {
    MatButtonModule,
    MatMenuModule,
    MatToolbarModule,
    MatSidenavModule,
    MatListModule,
    MatIconModule,
    MatCardModule,
    MatTabsModule,
    MatTooltipModule,
    MatExpansionModule,
    MatStepperModule,
    MatDialogModule,
    MatOptionModule,
    MatSelectModule,
    MatFormFieldModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatInputModule,
    MatCheckboxModule,
    MatSlideToggleModule,
    MatSnackBarModule,
    MatProgressBarModule
  } from '@angular/material';

  @NgModule({
    imports: [
      MatButtonModule,
      MatDatepickerModule,
      MatMenuModule,
      MatToolbarModule,
      MatSidenavModule,
      MatListModule,
      MatFormFieldModule,
      MatInputModule,
      MatIconModule,
      MatCardModule,
      MatTabsModule,
      MatTooltipModule,
      MatExpansionModule,
      MatStepperModule,
      MatDialogModule,
      MatOptionModule,
      MatSelectModule,
      MatNativeDateModule,
      MatCheckboxModule,
      MatSlideToggleModule,
      MatDialogModule,
      MatFormFieldModule,
      MatButtonModule,
      MatSnackBarModule,
      MatProgressBarModule
    ],
    exports: [
      MatButtonModule,
      MatMenuModule,
      MatToolbarModule,
      MatSidenavModule,
      MatSelectModule,
      MatFormFieldModule,
      MatDatepickerModule,
      MatInputModule,
      MatListModule,
      MatIconModule,
      MatCardModule,
      MatTabsModule,
      MatExpansionModule,
      MatTooltipModule,
      MatExpansionModule,
      MatStepperModule,
      MatDialogModule,
      MatOptionModule,
      MatSelectModule,
      MatNativeDateModule,
      MatCheckboxModule,
      MatSlideToggleModule,
      MatDialogModule,
      MatFormFieldModule,
      MatButtonModule,
      MatSnackBarModule,
      MatProgressBarModule
    ]
  })
  export class MaterialModule {}
